/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as FoodieSignupRouteImport } from './routes/foodie-signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMerchantRouteImport } from './routes/_authenticated/merchant'
import { Route as AuthenticatedMyApplicationsRouteImport } from './routes/_authenticated/my-applications'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleCampaignsRouteImport } from './routes/console/campaigns'
import { Route as ConsoleCreatorsRouteImport } from './routes/console/creators'
import { Route as ConsoleMerchantsRouteImport } from './routes/console/merchants'
import { Route as ConsoleSubmissionsRouteImport } from './routes/console/submissions'
import { Route as ConsoleLoginRouteImport } from './routes/console_.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodieSignupRoute = FoodieSignupRouteImport.update({
  id: '/foodie-signup',
  path: '/foodie-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMerchantRoute = AuthenticatedMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyApplicationsRoute =
  AuthenticatedMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCampaignsRoute = ConsoleCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCreatorsRoute = ConsoleCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMerchantsRoute = ConsoleMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSubmissionsRoute = ConsoleSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleLoginRoute = ConsoleLoginRouteImport.update({
  id: '/console_/login',
  path: '/console/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/foodie-signup': typeof FoodieSignupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/merchant': typeof AuthenticatedMerchantRoute
  '/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/console/campaigns': typeof ConsoleCampaignsRoute
  '/console/creators': typeof ConsoleCreatorsRoute
  '/console/merchants': typeof ConsoleMerchantsRoute
  '/console/submissions': typeof ConsoleSubmissionsRoute
  '/console/login': typeof ConsoleLoginRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/foodie-signup': typeof FoodieSignupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/merchant': typeof AuthenticatedMerchantRoute
  '/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/console/campaigns': typeof ConsoleCampaignsRoute
  '/console/creators': typeof ConsoleCreatorsRoute
  '/console/merchants': typeof ConsoleMerchantsRoute
  '/console/submissions': typeof ConsoleSubmissionsRoute
  '/console/login': typeof ConsoleLoginRoute
  '/console': typeof ConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/foodie-signup': typeof FoodieSignupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/merchant': typeof AuthenticatedMerchantRoute
  '/_authenticated/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/console/campaigns': typeof ConsoleCampaignsRoute
  '/console/creators': typeof ConsoleCreatorsRoute
  '/console/merchants': typeof ConsoleMerchantsRoute
  '/console/submissions': typeof ConsoleSubmissionsRoute
  '/console_/login': typeof ConsoleLoginRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/auth'
    | '/foodie-signup'
    | '/reset-password'
    | '/admin'
    | '/merchant'
    | '/my-applications'
    | '/console/campaigns'
    | '/console/creators'
    | '/console/merchants'
    | '/console/submissions'
    | '/console/login'
    | '/console/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/foodie-signup'
    | '/reset-password'
    | '/admin'
    | '/merchant'
    | '/my-applications'
    | '/console/campaigns'
    | '/console/creators'
    | '/console/merchants'
    | '/console/submissions'
    | '/console/login'
    | '/console'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/console'
    | '/auth'
    | '/foodie-signup'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/merchant'
    | '/_authenticated/my-applications'
    | '/console/campaigns'
    | '/console/creators'
    | '/console/merchants'
    | '/console/submissions'
    | '/console_/login'
    | '/console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FoodieSignupRoute: typeof FoodieSignupRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ConsoleLoginRoute: typeof ConsoleLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foodie-signup': {
      id: '/foodie-signup'
      path: '/foodie-signup'
      fullPath: '/foodie-signup'
      preLoaderRoute: typeof FoodieSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant': {
      id: '/_authenticated/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof AuthenticatedMerchantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-applications': {
      id: '/_authenticated/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof AuthenticatedMyApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/campaigns': {
      id: '/console/campaigns'
      path: '/campaigns'
      fullPath: '/console/campaigns'
      preLoaderRoute: typeof ConsoleCampaignsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/creators': {
      id: '/console/creators'
      path: '/creators'
      fullPath: '/console/creators'
      preLoaderRoute: typeof ConsoleCreatorsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/merchants': {
      id: '/console/merchants'
      path: '/merchants'
      fullPath: '/console/merchants'
      preLoaderRoute: typeof ConsoleMerchantsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/submissions': {
      id: '/console/submissions'
      path: '/submissions'
      fullPath: '/console/submissions'
      preLoaderRoute: typeof ConsoleSubmissionsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console_/login': {
      id: '/console_/login'
      path: '/console/login'
      fullPath: '/console/login'
      preLoaderRoute: typeof ConsoleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMerchantRoute: typeof AuthenticatedMerchantRoute
  AuthenticatedMyApplicationsRoute: typeof AuthenticatedMyApplicationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMerchantRoute: AuthenticatedMerchantRoute,
  AuthenticatedMyApplicationsRoute: AuthenticatedMyApplicationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ConsoleRouteRouteChildren {
  ConsoleCampaignsRoute: typeof ConsoleCampaignsRoute
  ConsoleCreatorsRoute: typeof ConsoleCreatorsRoute
  ConsoleMerchantsRoute: typeof ConsoleMerchantsRoute
  ConsoleSubmissionsRoute: typeof ConsoleSubmissionsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleCampaignsRoute: ConsoleCampaignsRoute,
  ConsoleCreatorsRoute: ConsoleCreatorsRoute,
  ConsoleMerchantsRoute: ConsoleMerchantsRoute,
  ConsoleSubmissionsRoute: ConsoleSubmissionsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FoodieSignupRoute: FoodieSignupRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ConsoleLoginRoute: ConsoleLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
